package com.udea.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PasajeroAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasajeroAllPropertiesEquals(Pasajero expected, Pasajero actual) {
        assertPasajeroAutoGeneratedPropertiesEquals(expected, actual);
        assertPasajeroAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasajeroAllUpdatablePropertiesEquals(Pasajero expected, Pasajero actual) {
        assertPasajeroUpdatableFieldsEquals(expected, actual);
        assertPasajeroUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasajeroAutoGeneratedPropertiesEquals(Pasajero expected, Pasajero actual) {
        assertThat(actual)
            .as("Verify Pasajero auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasajeroUpdatableFieldsEquals(Pasajero expected, Pasajero actual) {
        assertThat(actual)
            .as("Verify Pasajero relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getApellido()).as("check apellido").isEqualTo(expected.getApellido()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getFechaNacimiento()).as("check fechaNacimiento").isEqualTo(expected.getFechaNacimiento()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasajeroUpdatableRelationshipsEquals(Pasajero expected, Pasajero actual) {
        // empty method
    }
}
